portal/urls.py
from django.conf.urls import url

from . import views

urlpatterns = (
    url(r'^$', views.index, name='index'),
    url(r'^home/$', views.home, name='home'),
    url(r'^home/(?P<userID_from_url>[0-9]+)/$', views.home, name='home'),
    url(r'^addHours/(?P<adminID>[0-9]+)/$', views.addHours, name='addHOurs'),
    url(r'^chat/(?P<clientID>[0-9]+)/(?P<adminID>[0-9]+)/$', views.chat, name='chat'),
    url(r'^call/(?P<clientID>[0-9]+)/(?P<adminID>[0-9]+)/$', views.call, name='call'),
    url(r'^admin_call/(?P<clientID>[0-9]+)/(?P<adminID>[0-9]+)/$', views.admin_call, name='admin_call'),
    url(r'^admin_chat/(?P<clientID>[0-9]+)/(?P<adminID>[0-9]+)/$', views.admin_chat, name='admin_chat'),
    url(r'^book/(?P<clientID>[0-9]+)/(?P<adminID>[0-9]+)/$', views.book, name='book'),
    url(r'^deleteHours/(?P<adminID>[0-9]+)/(?P<officeHoursID>[0-9]+)/$', views.deleteHours, name='deleteHours'),
    url(r'^acceptRequest/(?P<clientID>[0-9]+)/(?P<adminID>[0-9]+)/$', views.acceptRequest, name='acceptRequest'),
    url(r'^getData/(?P<clientID>[0-9]+)/(?P<adminID>[0-9]+)/$', views.getData, name='getData'),
    url(r'^admin_getData/(?P<clientID>[0-9]+)/(?P<adminID>[0-9]+)/$', views.admin_getData, name='admin_getData'),
    url(r'^index/$', views.my_logout, name='logout'),
    url(r'^feedback/(?P<clientID>[0-9]+)/$', views.feedback, name='feedback'),
    url(r'^addFB/(?P<clientID>[0-9]+)/$', views.addFB, name='addFB'),
    url(r'^about/(?P<userID>[0-9]+)/$', views.about, name='about'),

    url(r'^polling_home/(?P<clientID>[0-9]+)/$', views.polling_home, name='polling_home'),
    url(r'^admin_polling_home/(?P<adminID>[0-9]+)/$', views.admin_polling_home, name='admin_polling_home'),
)

project/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^portal/', include('portal.urls',namespace='portal')),
)

portal/models.py
from django.db import models
from django.utils.encoding import python_2_unicode_compatible


class MyUser(models.Model):
	username=models.CharField(max_length=40)
	password=models.CharField(max_length=40)
	is_admin=models.BooleanField(default=False)
	sent_new_text=models.BooleanField(default=False)
	is_online=models.BooleanField(default=False)

	updated_office_hours=models.BooleanField(default=False)
	status_appointment_changed=models.BooleanField(default=False)
	updated_time_slots=models.BooleanField(default=False)



	def __str__(self):
		return self.username


class Query(models.Model):
	client=models.ForeignKey(MyUser, on_delete=models.CASCADE, related_name='client_text')
	admin=models.ForeignKey(MyUser, on_delete=models.CASCADE, related_name='admin_text')
	pub_date=models.DateTimeField('date published')
	text=models.CharField(max_length=200)
	by_admin=models.BooleanField(default=False)

	def __str__(self):
		return self.text


class OfficeHour(models.Model):
	admin=models.ForeignKey(MyUser, on_delete=models.CASCADE)
	start_time=models.CharField(max_length=10)
	end_time=models.CharField(max_length=10)
	display=models.CharField(max_length=20)

	def __str__(self):
		return self.display


class TimeSlot(models.Model):
	client=models.ForeignKey(MyUser, on_delete = models.CASCADE, related_name = 'client_slot', null = True)
	office_hours=models.ForeignKey(OfficeHour, on_delete=models.CASCADE, related_name = 'office_slot')
	display=models.CharField(max_length=40)
	is_free=models.BooleanField(default=True)		#if free then delete appoitment entry

	def __str__(self):
		return self.display

class Appointment(models.Model):
	client=models.ForeignKey(MyUser, on_delete=models.CASCADE, related_name='client_time')
	admin=models.ForeignKey(MyUser, on_delete=models.CASCADE, related_name='admin_time')
	slot=models.ForeignKey(TimeSlot, on_delete=models.CASCADE, related_name='slot_time')
	status=models.CharField(max_length=20, default='pending')		#if free then delete entry

	def __str__(self):
		return self.status


class Feedback(models.Model):
	client=models.ForeignKey(MyUser, on_delete=models.CASCADE, related_name='client_feedback')
	admin=models.ForeignKey(MyUser, on_delete=models.CASCADE, related_name='admin_feedback', null = True)
	ans1=models.CharField(max_length=100)
	ans2=models.CharField(max_length=100)
	ans3=models.CharField(max_length=100)
	ans4=models.CharField(max_length=100)
	ans5=models.CharField(max_length=100)
	ans6=models.CharField(max_length=100)
	
	

portal/views.py
from django.shortcuts import render
from django.core.mail.backends import console
from django.shortcuts import render, render_to_response
from django.template import RequestContext
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from datetime import datetime
#for csrf extempt
from django.views.decorators.csrf import csrf_exempt

from django.contrib.auth import authenticate
from django.contrib.auth import logout
from django.contrib.auth.models import User

import json


from .models import MyUser, Query, OfficeHour, TimeSlot, Appointment, Feedback


def index(request):
    context={}
    return render(request, 'portal/index.html', context)


def home(request, userID_from_url=None):
    
    if userID_from_url is None :
        flag=request.POST.get('login_flag')
        

        if(flag=='signup'):
            

            uname = request.POST.get('username')
            pword1 = request.POST.get('password1')
            pword2 = request.POST.get('password2')
            

            

            tempUser=MyUser.objects.filter(username=uname)
            if tempUser:                                            ########### use tempUser[0]
                context={
                    'err': 'Username is not valid. Please try a different one',
                }
                return render(request, 'portal/error.html', context)

            if (pword1 == pword2):
                allAdmins = MyUser.objects.filter(is_admin=True)
                currentClient = MyUser.objects.create(username=uname, password=pword1, is_online=True)
                
                request.session['user_id'] = currentClient.id

                allAppointments=Appointment.objects.filter(client=currentClient)

                user = User.objects.create_user(uname, None, pword1)

                context={
                    'client':currentClient,
                    'all':allAdmins,
                    'message':'you just made a new account, get excited',
                    'allAppointments': allAppointments,
                }
                return render(request, 'portal/home.html', context)

            else:
                context={
                    'err': 'Your passwords didn\'t match',
                }
                return render(request, 'portal/error.html', context)
        
        elif(flag=='login'):
            uname = request.POST.get('username')
            pword = request.POST.get('password')
            
            tempUser = MyUser.objects.filter(username=uname)


            user = authenticate(username=uname, password=pword)

            if user is None:
                if not tempUser:
                    return render(request, 'portal/error.html', {'err': 'Username doesn\'t exist'})
                
                elif tempUser[0].password != pword:
                    return render(request, 'portal/error.html', {'err': 'Incorrect password'})
            
            elif user is not None:
                
                request.session['user_id'] = tempUser[0].id
                
                if tempUser[0].is_admin:
                    currentAdmin=tempUser[0]
                    MyUser.objects.filter(username=currentAdmin.username).update(is_online=True)
                    officeHours= OfficeHour.objects.filter(admin=currentAdmin)
                    allClients = MyUser.objects.filter(is_admin=False)
                    allAppointments=Appointment.objects.filter(admin=currentAdmin)

                    context={
                        'admin':currentAdmin,
                        'all':allClients,
                        'office_hours':officeHours,
                        'allAppointments':allAppointments,

                    }
                    return render(request, 'portal/admin_home.html', context)

                elif not tempUser[0].is_admin :
                    currentClient=tempUser[0]
                    MyUser.objects.filter(username=currentClient.username).update(is_online=True)
                    appointment_time='';
                    allAdmins = MyUser.objects.filter(is_admin=True)
                    allAppointments=Appointment.objects.filter(client=currentClient)
                    context={
                        'a':request.session['user_id'],
                        'b':tempUser[0].id,
                        'client':currentClient,
                        'all':allAdmins,
                        'message':'you are logged in',
                        'allAppointments': allAppointments,

                    }
                    return render(request, 'portal/home.html', context)

        elif(flag == 'after_book'):
            try:
                t=request.session['user_id']
            except KeyError:
                context1={
                    'err':'Please login to access the portal',
                    'link':"portal:index",
                }
                return render(request, 'portal/error.html', context1)
            clientID=request.POST.get('clientID')
            if str(request.session['user_id']) == str(clientID):

                adminID=request.POST.get('adminID')
                slot_display=request.POST.get('slot_time')
                currentClient=MyUser.objects.get(pk=clientID)
                currentAdmin=MyUser.objects.get(pk=adminID)

                office_hours=OfficeHour.objects.filter(admin=currentAdmin)
                
                if office_hours:
                    TimeSlot.objects.filter(display = slot_display, office_hours = office_hours).update(is_free = False, client = currentClient)
                    
                    tempTimeSlot=TimeSlot.objects.filter(display = slot_display, office_hours = office_hours)

                    Appointment.objects.create(client=currentClient, admin=currentAdmin, slot= tempTimeSlot[0]) 
                    MyUser.objects.filter(pk=clientID).update(status_appointment_changed=True)
                    MyUser.objects.filter(pk=adminID).update(status_appointment_changed=True)
                return HttpResponseRedirect(reverse('portal:home', args=(clientID,)))
            else:
                context={
                    'err':'Invalid authorization'
                }
                return render(request, 'portal/error.html', context)


        elif(flag == 'redirect'):
            try:
                t=request.session['user_id']
            except KeyError:
                context1={
                    'err':'Please login to access the portal',
                    'link':"portal:index",
                }
                return render(request, 'portal/error.html', context1)
            userID=request.POST.get('userID')
            if str(request.session['user_id']) == str(userID):
                return HttpResponseRedirect(reverse('portal:home', args=(userID,)))
            else:
                context={
                    'err':'Invalid authorization'
                }
                return render(request, 'portal/error.html', context)
            

    else:
        try:
            t=request.session['user_id']
        except KeyError:
            context1={
                'err':'Please login to access the portal',
                'link':"portal:index",
            }
            return render(request, 'portal/error.html', context1)

        userID=userID_from_url

        if str(request.session['user_id']) == str(userID):
            currentUser=MyUser.objects.get(pk=userID)
                
            
            if currentUser.is_admin:
                adminID=userID
                currentAdmin=MyUser.objects.get(pk=adminID)

                allClients=MyUser.objects.filter(is_admin=False)
                officeHours= OfficeHour.objects.filter(admin=currentAdmin)
                allAppointments=Appointment.objects.filter(admin=currentAdmin)
                context={
                    'admin':currentAdmin,
                    'all':allClients,
                    'office_hours':officeHours,
                    'allAppointments':allAppointments,
                }
                return render(request, 'portal/admin_home.html', context)

            else:
                clientID=userID
                currentClient=MyUser.objects.get(pk=clientID)
                
                allAdmins= MyUser.objects.filter(is_admin=True)                                                             
                allAppointments=Appointment.objects.filter(client=currentClient)     

                context={
                    'client':currentClient,
                    'all':allAdmins,
                    'message':'you are logged in',
                    'allAppointments':allAppointments,
                }
                return render(request, 'portal/home.html', context)

        else:
            context={
                'err':'Invalid authorization'
            }
            return render(request, 'portal/error.html', context)





def addHours(request, adminID):
    try:
        t=request.session['user_id']
    except KeyError:
        context1={
            'err':'Please login to access the portal',
            'link':"portal:index",
        }
        return render(request, 'portal/error.html', context1)
    if str(request.session['user_id']) == str(adminID):
        start_time = request.POST.get('start_time')
        end_time = request.POST.get('end_time')
        currentAdmin=MyUser.objects.get(pk=adminID)
        if start_time is not None and start_time != '' and end_time is not None and end_time != '' :
        
            hours=OfficeHour.objects.create(admin=currentAdmin,start_time=start_time,end_time=end_time,display=start_time+' to '+end_time)
            start_hour=''
            start_min=''
            start_m=''
            end_hour=''
            end_min=''
            end_m=''
            
            
            for x in range(8):

portal/templates/portal/about.html
{% include "navbar.html" with user=user %}

{{msg}}

portal/templates/portal/admin_call.html
<html>
<link rel="stylesheet" href="https://code.getmdl.io/1.1.3/material.indigo-pink.min.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<script defer src="https://code.getmdl.io/1.1.3/material.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"></script>
<meta charset="utf-8"/>
<style type="text/css">
	body{
		background-color: #9999ff;
	}
</style>

{% include "navbar.html" with user=admin %}

<div id="vid-box"></div>

<form name="loginForm" id="login" action="#" onsubmit="return login(this);">
    <input type="submit" name="login_submit" value="Connect">
</form>

<form name="callForm" id="call" action="#" onsubmit="return makeCall(this);">
	<input type="submit" value="Call"/>
</form>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="https://cdn.pubnub.com/pubnub-3.7.14.min.js"></script>
<script src="https://cdn.pubnub.com/webrtc/webrtc.js"></script>

<script type="text/javascript">
	var video_out = document.getElementById("vid-box");

	function login(form) {
		var phone = window.phone = PHONE({
		    number        : '{{admin.username}}' || "Anonymous", // listen on username line else Anonymous
		    publish_key   : 'pub-c-cba17aca-c1fe-4e0a-bf09-75f8ae0d449c',
		    subscribe_key : 'sub-c-0422179e-2fe4-11e6-b700-0619f8945a4f',
		});	
		phone.ready(function(){ alert("You can either call {{client.username}} or wait for a call"); });
		phone.receive(function(session){
		    session.connected(function(session) { video_out.appendChild(session.video); });
		    session.ended(function(session) { video_out.innerHTML=''; });
		});
		return false; 	// So the form does not submit.
	}

	function makeCall(form){
		if (!window.phone) alert("Connect and then try to call!");
		else phone.dial('{{client.username}}');
		return false;
	}


</script>
</html>

portal/templates/portal/admin_home.html
<a href="{% url 'portal:logout' %}">Logout</a>
<br>



{% if all %}
    <ul>
    {% for x in all %}
        <li>{{x.username}}
        <a href="{% url 'portal:admin_chat' x.id admin.id%}">Chat</a>
        <a href="{% url 'portal:admin_call' x.id admin.id%}">Call</a>
        {% if allAppointments %}
            {% for y in allAppointments %}
                {% if x == y.client %}
                    {% if y.status == 'booked' %}
                        Appointmented at {{y.slot.display}}
                    {% elif y.status == 'pending' %}
                        Pending appointment request at {{y.slot.display}}
                        
                        <form action="{% url 'portal:acceptRequest' x.id admin.id%}" method="POST">
                            {% csrf_token %}
                             <input type="hidden" value="accept" name="accept_flag">
                            <input type="submit" value="Accept">
                        </form>

                        <form action="{% url 'portal:acceptRequest' x.id admin.id%}" method="POST">
                            {% csrf_token %}
                             <input type="hidden" value="decline" name="accept_flag">
                            <input type="submit" value="Decline">
                        </form>
                    {% else %}
                          No appointment
                    {% endif %}
                {% endif %}
            {% endfor %}
        {% else %}
            No appointment
        {% endif %}
        </li>
    {% endfor %}
    </ul>
{% else %}
    <p>No client</p>
{% endif %}

<h3>Your office hours:</h3>
{% if office_hours %}
    <ul>
    {% for x in office_hours %}
        <li>{{ x.display }}  <a href="#" onClick= "deleteOfficeHours('{{x.id}}'); return false;" >Delete hours</a></li>
    {% endfor %}
    </ul>
{% endif %}

<h3>Add office hours:</h3>

<form action="{% url 'portal:addHOurs' admin.id%}" method="POST">

  {% csrf_token %}
  <div>Start time: <input type="text" id="time1" size="10" value="" name='start_time'/></div>
  <div>End time: <input type="text" id="time2" size="10" value="" name='end_time'/></div>
  
  <input type="submit" value="Submit">
</form>

{% load staticfiles %}
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.js"></script>
<script src="{% static 'portal/jquery.timePicker.js' %}" ></script>
<script src="{% static 'portal/jquery.timePicker.min.js' %}" ></script>




<script type="text/javascript">
  $("#time1").timePicker({
  startTime: "09.00", // Using string. Can take string or Date object.
  endTime: new Date(0, 0, 0, 17, 0, 0), // Using Date object here.
  show24Hours: false,
  separator: '.',
  step: 30});

  $("#time2").timePicker({
  startTime: "09.00", // Using string. Can take string or Date object.
  endTime: new Date(0, 0, 0, 17, 0, 0), // Using Date object here.
  show24Hours: false,
  separator: '.',
  step: 30});

</script>

<script type="text/javascript">
    function deleteOfficeHours(office_hours_id)
    {
        $.get("/portal/deleteHours/{{admin.id}}/"+office_hours_id+"/", function(data, status)
        {
            data = JSON.parse(data);
            val =data['type'];
            console.log("Data: " + val + "\nStatus: " + status);
            if (val==1)
            {
                location.reload();
            }
        }); 
    }
</script>


<script>
function afterLoad() {

        setInterval(function(){ myFunction(); }, 10000);

}

window.onload=afterLoad();

function myFunction()
{
    $.get("/portal/admin_polling_home/{{admin.id}}/", function(data, status)
        {
            data = JSON.parse(data);
            val =data['type'];
            console.log("Data: " + val + "\nStatus: " + status);
            if (val==1)
            {
                //do nothing
            }
            else if(val==2)
            {
               location.reload();
            }
        }); 
}
</script>

portal/templates/portal/book.html
{% if flag %}      
      You already have an apointment from {{appointment_at.slot}}
      <br>
      <button onclick="goBack()">Back</button>
{% else %}
      {% include 'appoint.html' with slots=slots %}
{% endif %}

<script>
function goBack() {
    window.history.back();
}
</script>

portal/templates/portal/error.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<style type="text/css">
		h1{
			color:white;
			font-size:10vw;
			text-shadow: 2px 2px #788881;
			text-align: center;
			margin-top: 15vw;
		}
		#link{
			text-decoration: none;
			color: white;
			font-size: 3vw;
		}
	</style>
</head>
<body style="background-color:#7176e6;">
{% if err%}<h1>{{err}}</h1>{%endif%}

{% if link %}
<a href="{% url link %}" id="link">GO!!!</a>
{% endif %}
</body>
</html>

portal/templates/portal/home.html
{% include "navbar.html" with user=client %}


<p id="login_text">Hello {{client.username}},{{message}} </p>

<br>




{% if all %}
    <ul>
    {% for x in all %}
        <li>
            <br>
            <div id="main_div">
        	<span id="usernames">{{x.username}}</span><br><br>
            <div style="margin-left:5%">
                <a href="{% url 'portal:chat' client.id x.id%}" class="mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect" style=" background-color:#8533ff;">
                    <i class="material-icons" style="color:#fff;"  >person_add</i>
                    <h6>Chat</h6>
                </a>
                <a href="{% url 'portal:call' client.id x.id%}" class="mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect" style=" background-color:#8533ff; margin-left:2%;">
                    <i class="material-icons" style="color:#fff;">videocam</i>
                    <h6>Call</h6>
                </a>
                <a href="{% url 'portal:book' client.id x.id%}" class="mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect" style=" background-color:#8533ff; margin-left:2%;">
                    <i class="material-icons" style="color:#fff;"  >person_pin</i>
                    <h6>Appointment</h6>
                </a>
                {% if allAppointments %}
                    {% for y in allAppointments %}
                        {% if x == y.admin %}
                            {% if y.status == 'booked' %}
                                Your appointment is at {{y.slot.display}}
                            {% elif y.status == 'pending' %}
                                Your request is pending
                            {% else %}
                                No appointment
                            {% endif %}
                        {% endif %}
                    {% endfor %}
                {% else %}
                    No appointment
                {% endif %}
            </div>
        	</div>
        </li>
    {% endfor %}
    </ul>
{% else %}
    <p>No admin</p>
{% endif %}

<br>
<br>
<a class="mdl-button mdl-js-button mdl-js-ripple-effect" href="{% url 'portal:feedback' client.id %}" style="margin-left:5%; background-color:#8533ff; color:#fff;">Feedback</a>
<a class="mdl-button mdl-js-button mdl-js-ripple-effect" id="logout_link" href="{% url 'portal:logout' %}" style="margin-left:5%; background-color:#8533ff; color:#fff;">Logout</a>
<script>
function goBack() {
    window.history.back();
}
</script>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>

<script>
function afterLoad() {

        setInterval(function(){ myFunction(); }, 10000);

}

window.onload=afterLoad();

function myFunction()
{
    $.get("/portal/polling_home/{{client.id}}/", function(data, status)
        {
            data = JSON.parse(data);
            val =data['type'];
            console.log("Data: " + val + "\nStatus: " + status);
            if (val==1)
            {
                //do nothing
            }
            else if(val==2)
            {
               location.reload();
            }
        }); 
}
</script>

portal/templates/portal/p_chat.html
  {% extends 'layout.html' %}
  


                      {% block card_left_title %}
                        {% if isAdmin %}
                            Clients
                        {% else %}
                            Admins
                        {% endif %}
                      {% endblock %}
                      



                      {% block card_left_supporting_text_list %}
                            

                        {% for x in sideList %}
                                  <li class="mdl-list__item">
                                    <span class="mdl-list__item-primary-content">
                                    <i class="material-icons mdl-list__item-icon">person</i>
                                    {% if isAdmin %}
                                        <a href="{% url 'portal:admin_chat' x.id admin.id%}">{{x.username}}</a>
                                    {% else %}
                                        <a href="{% url 'portal:chat' client.id x.id%}">{{x.username}}</a>
                                    {% endif %}
                                  </span>
                                  </li>
                            {% endfor %}
                      {% endblock %}
             
                    {% block card_left_buttons %}
                        <a class="mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect" style=" margin-left:2vw;background-color:#8533ff;" id="feedback_page">
                          <i class="material-icons" style="color:#fff;">feedback</i>
                          <h6>Feedback</h6>
                        </a>
                        <a class="mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect" style=" margin-left:2vw;background-color:#8533ff;" id="video_page" >
                          <i class="material-icons" style="color:#fff;" >videocam</i>
                          <h6>Call</h6>
                        </a>
                        <a class="mdl-button  mdl-js-button mdl-button--fab mdl-js-ripple-effect" style=" margin-left:2vw;background-color:#8533ff;" id="appointment_page">
                          <i class="material-icons" style="color:#fff;">person_pin</i>
                          <h6>Appointment</h6>
                        </a>
                      {% endblock %}


                    {% block card_right_title %}

                        {% if isAdmin %}
                            {{client.username}}
                        {% else %}
                            {{admin.username}}
                        {% endif %}
                      
                    {% endblock %}
   
                {% block card_right_supporting_text %}    


                    
                    {% if all %}
                    <ul class="demo-list mdl-list">
                     <div id="chat"> 
                      
                          {% for x in all %}
                            {% include "p_chat_userchat.html" with x=x%}
                          {% endfor %}
                      
                      </div>
                      </ul>
                    {% else %}
                        <p>You didn't chat until now</p>
                    {% endif %}
                      
                {% endblock %}    
                    
                 {% block card_right_bottom %}    
                      <div class="mdl-card__supporting-text">
                          <form {% if isAdmin %}
                                    action="{% url 'portal:admin_chat' client.id admin.id %}"
                                {% else %}    
                                    action="{% url 'portal:chat' client.id admin.id %}" 
                                {% endif %} 
                                method="POST" id="forms">
                            {% csrf_token %}
                            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                              <textarea id="id_of_textbox" class="mdl-textfield__input" type="text" rows= "3" id="sample5" name="new_msg"></textarea>
                              <label class="mdl-textfield__label" for="sample5">Enter your message</label>
                              </div>
                                <button style="float:right; background-color:#8533ff; size:3px;"  id="id_of_button" class="mdl-button mdl-button--fab mdl-js-button mdl-js-ripple-effect" type="submit" value="Send"><i class="material-icons" style="color:#fff;">send</i></button>
                          </form>
                      </div>
                    {% endblock %}    
                


{% block script %}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>

<script type="text/javascript">
    $("#id_of_textbox").keyup(function(event){
      if(event.keyCode == 13  &&  !event.shiftKey){
          $("#id_of_button").click();
      }
  });
</script>












<script>
function afterLoad() {

    {% if isAdmin %}
        setInterval(function(){ adminFunction(); }, 5000);
    {% else %}
        setInterval(function(){ clientFunction(); }, 5000);
    {% endif %}
}

window.onload=afterLoad();






function clientFunction()
{
    $.get("/portal/getData/{{client.id}}/{{admin.id}}/", function(data, status)
        {
            data = JSON.parse(data);
            val =data['type'];
            console.log("Data: " + val + "\nStatus: " + status);
            if (val==1)
            {
                //do nothing
            }
            else if(val==2)
            {
                $("#chat").load("{% url 'portal:chat' client.id admin.id %} #chat");
                //location.reload();
            }
        }); 
}


function adminFunction()
{
    $.get("/portal/admin_getData/{{client.id}}/{{admin.id}}/", function(data, status)
        {
            data = JSON.parse(data);
            val =data['type'];
            console.log("Data: " + val + "\nStatus: " + status);
            if (val==1)
            {
                //do nothing
            }
            else if(val==2)
            {
                $("#chat").load("{% url 'portal:admin_chat' client.id admin.id %} #chat");
                //location.reload();
            }
        }); 
}
</script>


<script >
function goBack() {
    window.history.back();
}
</script>

<script>
// $("#scroll_bottom").animate({ scrollTop: $(document).height()+1000 }, "slow");
document.getElementById('scroll_bottom').scrollTop = 99999999999;
</script>

<!-- <script type="text/javascript">
    $("#appointment_page").click(function(){
        window.location.href = "appoint.html";
    });
    $("#video_page").click(function(){
        window.location.href = "video.html";
    });
    $("#feedback_page").click(function(){
        window.location.href = "feedback.html";
    });
  </script> -->

{% endblock %}