portal/urls.py
from django.conf.urls import url

from . import views

urlpatterns = (
    url(r'^$', views.index, name='index'),
    url(r'^home/$', views.home, name='home'),
    url(r'^home/(?P<userID_from_url>[0-9]+)/$', views.home, name='home'),
    url(r'^addHours/(?P<adminID>[0-9]+)/$', views.addHours, name='addHOurs'),
    url(r'^chat/(?P<clientID>[0-9]+)/(?P<adminID>[0-9]+)/$', views.chat, name='chat'),
    url(r'^call/(?P<clientID>[0-9]+)/(?P<adminID>[0-9]+)/$', views.call, name='call'),
    url(r'^admin_call/(?P<clientID>[0-9]+)/(?P<adminID>[0-9]+)/$', views.admin_call, name='admin_call'),
    url(r'^admin_chat/(?P<clientID>[0-9]+)/(?P<adminID>[0-9]+)/$', views.admin_chat, name='admin_chat'),
    url(r'^book/(?P<clientID>[0-9]+)/(?P<adminID>[0-9]+)/$', views.book, name='book'),
    url(r'^deleteHours/(?P<adminID>[0-9]+)/(?P<officeHoursID>[0-9]+)/$', views.deleteHours, name='deleteHours'),
    url(r'^acceptRequest/(?P<clientID>[0-9]+)/(?P<adminID>[0-9]+)/$', views.acceptRequest, name='acceptRequest'),
    url(r'^getData/(?P<clientID>[0-9]+)/(?P<adminID>[0-9]+)/$', views.getData, name='getData'),
    url(r'^admin_getData/(?P<clientID>[0-9]+)/(?P<adminID>[0-9]+)/$', views.admin_getData, name='admin_getData'),
    url(r'^index/$', views.my_logout, name='logout'),
    url(r'^feedback/(?P<clientID>[0-9]+)/$', views.feedback, name='feedback'),
    url(r'^addFB/(?P<clientID>[0-9]+)/$', views.addFB, name='addFB'),
    url(r'^about/(?P<userID>[0-9]+)/$', views.about, name='about'),

    url(r'^polling_home/(?P<clientID>[0-9]+)/$', views.polling_home, name='polling_home'),
    url(r'^admin_polling_home/(?P<adminID>[0-9]+)/$', views.admin_polling_home, name='admin_polling_home'),
)

project/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^portal/', include('portal.urls',namespace='portal')),
)

portal/models.py
from django.db import models
from django.utils.encoding import python_2_unicode_compatible


class MyUser(models.Model):
	username=models.CharField(max_length=40)
	password=models.CharField(max_length=40)
	is_admin=models.BooleanField(default=False)
	sent_new_text=models.BooleanField(default=False)
	is_online=models.BooleanField(default=False)

	updated_office_hours=models.BooleanField(default=False)
	status_appointment_changed=models.BooleanField(default=False)
	updated_time_slots=models.BooleanField(default=False)



	def __str__(self):
		return self.username


class Query(models.Model):
	client=models.ForeignKey(MyUser, on_delete=models.CASCADE, related_name='client_text')
	admin=models.ForeignKey(MyUser, on_delete=models.CASCADE, related_name='admin_text')
	pub_date=models.DateTimeField('date published')
	text=models.CharField(max_length=200)
	by_admin=models.BooleanField(default=False)

	def __str__(self):
		return self.text


class OfficeHour(models.Model):
	admin=models.ForeignKey(MyUser, on_delete=models.CASCADE)
	start_time=models.CharField(max_length=10)
	end_time=models.CharField(max_length=10)
	display=models.CharField(max_length=20)

	def __str__(self):
		return self.display


class TimeSlot(models.Model):
	client=models.ForeignKey(MyUser, on_delete = models.CASCADE, related_name = 'client_slot', null = True)
	office_hours=models.ForeignKey(OfficeHour, on_delete=models.CASCADE, related_name = 'office_slot')
	display=models.CharField(max_length=40)
	is_free=models.BooleanField(default=True)		#if free then delete appoitment entry

	def __str__(self):
		return self.display

class Appointment(models.Model):
	client=models.ForeignKey(MyUser, on_delete=models.CASCADE, related_name='client_time')
	admin=models.ForeignKey(MyUser, on_delete=models.CASCADE, related_name='admin_time')
	slot=models.ForeignKey(TimeSlot, on_delete=models.CASCADE, related_name='slot_time')
	status=models.CharField(max_length=20, default='pending')		#if free then delete entry

	def __str__(self):
		return self.status


class Feedback(models.Model):
	client=models.ForeignKey(MyUser, on_delete=models.CASCADE, related_name='client_feedback')
	admin=models.ForeignKey(MyUser, on_delete=models.CASCADE, related_name='admin_feedback', null = True)
	ans1=models.CharField(max_length=100)
	ans2=models.CharField(max_length=100)
	ans3=models.CharField(max_length=100)
	ans4=models.CharField(max_length=100)
	ans5=models.CharField(max_length=100)
	ans6=models.CharField(max_length=100)
	
	

portal/views.py
from django.shortcuts import render
from django.core.mail.backends import console
from django.shortcuts import render, render_to_response
from django.template import RequestContext
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from datetime import datetime
#for csrf extempt
from django.views.decorators.csrf import csrf_exempt

from django.contrib.auth import authenticate
from django.contrib.auth import logout
from django.contrib.auth.models import User

import json


from .models import MyUser, Query, OfficeHour, TimeSlot, Appointment, Feedback


def index(request):
    context={}
    return render(request, 'portal/index.html', context)


def home(request, userID_from_url=None):
    
    if userID_from_url is None :
        flag=request.POST.get('login_flag')
        

        if(flag=='signup'):
            

            uname = request.POST.get('username')
            pword1 = request.POST.get('password1')
            pword2 = request.POST.get('password2')
            

            

            tempUser=MyUser.objects.filter(username=uname)
            if tempUser:                                            ########### use tempUser[0]
                context={
                    'err': 'Username is not valid. Please try a different one',
                }
                return render(request, 'portal/error.html', context)

            if (pword1 == pword2):
                allAdmins = MyUser.objects.filter(is_admin=True)
                currentClient = MyUser.objects.create(username=uname, password=pword1, is_online=True)
                
                request.session['user_id'] = currentClient.id

                allAppointments=Appointment.objects.filter(client=currentClient)

                user = User.objects.create_user(uname, None, pword1)

                context={
                    'client':currentClient,
                    'all':allAdmins,
                    'message':'you just made a new account, get excited',
                    'allAppointments': allAppointments,
                }
                return render(request, 'portal/home.html', context)

            else:
                context={
                    'err': 'Your passwords didn\'t match',
                }
                return render(request, 'portal/error.html', context)
        
        elif(flag=='login'):
            uname = request.POST.get('username')
            pword = request.POST.get('password')
            
            tempUser = MyUser.objects.filter(username=uname)


            user = authenticate(username=uname, password=pword)

            if user is None:
                if not tempUser:
                    return render(request, 'portal/error.html', {'err': 'Username doesn\'t exist'})
                
                elif tempUser[0].password != pword:
                    return render(request, 'portal/error.html', {'err': 'Incorrect password'})
            
            elif user is not None:
                
                request.session['user_id'] = tempUser[0].id
                
                if tempUser[0].is_admin:
                    currentAdmin=tempUser[0]
                    MyUser.objects.filter(username=currentAdmin.username).update(is_online=True)
                    officeHours= OfficeHour.objects.filter(admin=currentAdmin)
                    allClients = MyUser.objects.filter(is_admin=False)
                    allAppointments=Appointment.objects.filter(admin=currentAdmin)

                    context={
                        'admin':currentAdmin,
                        'all':allClients,
                        'office_hours':officeHours,
                        'allAppointments':allAppointments,

                    }
                    return render(request, 'portal/admin_home.html', context)

                elif not tempUser[0].is_admin :
                    currentClient=tempUser[0]
                    MyUser.objects.filter(username=currentClient.username).update(is_online=True)
                    appointment_time='';
                    allAdmins = MyUser.objects.filter(is_admin=True)
                    allAppointments=Appointment.objects.filter(client=currentClient)
                    context={
                        'a':request.session['user_id'],
                        'b':tempUser[0].id,
                        'client':currentClient,
                        'all':allAdmins,
                        'message':'you are logged in',
                        'allAppointments': allAppointments,

                    }
                    return render(request, 'portal/home.html', context)

        elif(flag == 'after_book'):
            try:
                t=request.session['user_id']
            except KeyError:
                context1={
                    'err':'Please login to access the portal',
                    'link':"portal:index",
                }
                return render(request, 'portal/error.html', context1)
            clientID=request.POST.get('clientID')
            if str(request.session['user_id']) == str(clientID):

                adminID=request.POST.get('adminID')
                slot_display=request.POST.get('slot_time')
                currentClient=MyUser.objects.get(pk=clientID)
                currentAdmin=MyUser.objects.get(pk=adminID)

                office_hours=OfficeHour.objects.filter(admin=currentAdmin)
                
                if office_hours:
                    TimeSlot.objects.filter(display = slot_display, office_hours = office_hours).update(is_free = False, client = currentClient)
                    
                    tempTimeSlot=TimeSlot.objects.filter(display = slot_display, office_hours = office_hours)

                    Appointment.objects.create(client=currentClient, admin=currentAdmin, slot= tempTimeSlot[0]) 
                    MyUser.objects.filter(pk=clientID).update(status_appointment_changed=True)
                    MyUser.objects.filter(pk=adminID).update(status_appointment_changed=True)
                return HttpResponseRedirect(reverse('portal:home', args=(clientID,)))
            else:
                context={
                    'err':'Invalid authorization'
                }
                return render(request, 'portal/error.html', context)


        elif(flag == 'redirect'):
            try:
                t=request.session['user_id']
            except KeyError:
                context1={
                    'err':'Please login to access the portal',
                    'link':"portal:index",
                }
                return render(request, 'portal/error.html', context1)
            userID=request.POST.get('userID')
            if str(request.session['user_id']) == str(userID):
                return HttpResponseRedirect(reverse('portal:home', args=(userID,)))
            else:
                context={
                    'err':'Invalid authorization'
                }
                return render(request, 'portal/error.html', context)
            

    else:
        try:
            t=request.session['user_id']
        except KeyError:
            context1={
                'err':'Please login to access the portal',
                'link':"portal:index",
            }
            return render(request, 'portal/error.html', context1)

        userID=userID_from_url

        if str(request.session['user_id']) == str(userID):
            currentUser=MyUser.objects.get(pk=userID)
                
            
            if currentUser.is_admin:
                adminID=userID
                currentAdmin=MyUser.objects.get(pk=adminID)

                allClients=MyUser.objects.filter(is_admin=False)
                officeHours= OfficeHour.objects.filter(admin=currentAdmin)
                allAppointments=Appointment.objects.filter(admin=currentAdmin)
                context={
                    'admin':currentAdmin,
                    'all':allClients,
                    'office_hours':officeHours,
                    'allAppointments':allAppointments,
                }
                return render(request, 'portal/admin_home.html', context)

            else:
                clientID=userID
                currentClient=MyUser.objects.get(pk=clientID)
                
                allAdmins= MyUser.objects.filter(is_admin=True)                                                             
                allAppointments=Appointment.objects.filter(client=currentClient)     

                context={
                    'client':currentClient,
                    'all':allAdmins,
                    'message':'you are logged in',
                    'allAppointments':allAppointments,
                }
                return render(request, 'portal/home.html', context)

        else:
            context={
                'err':'Invalid authorization'
            }
            return render(request, 'portal/error.html', context)





def addHours(request, adminID):
    try:
        t=request.session['user_id']
    except KeyError:
        context1={
            'err':'Please login to access the portal',
            'link':"portal:index",
        }
        return render(request, 'portal/error.html', context1)
    if str(request.session['user_id']) == str(adminID):
        start_time = request.POST.get('start_time')
        end_time = request.POST.get('end_time')
        currentAdmin=MyUser.objects.get(pk=adminID)
        if start_time is not None and start_time != '' and end_time is not None and end_time != '' :
        
            hours=OfficeHour.objects.create(admin=currentAdmin,start_time=start_time,end_time=end_time,display=start_time+' to '+end_time)
            start_hour=''
            start_min=''
            start_m=''
            end_hour=''
            end_min=''
            end_m=''
            
            
            for x in range(8):

portal/templates/appoint.html
<!DOCTYPE html>
<html>
<head>
	<title>Psychology Portal IIITD</title>
	
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/css/materialize.min.css">
<!-- 	<link rel="stylesheet" type="text/css" href="style.css">
	<link rel="stylesheet" type="text/css" href="style.css"> -->
	<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
	<link rel="stylesheet" href="https://code.getmdl.io/1.1.3/material.indigo-pink.min.css">
	<script defer src="https://code.getmdl.io/1.1.3/material.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/js/materialize.min.js"></script>
	<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script type="text/javascript" src="js/materialize.min.js"></script>
    <link href='https://fonts.googleapis.com/css?family=Slabo+27px' rel='stylesheet' type='text/css'>
	 <style>
		@import url(https://fonts.googleapis.com/css?family=Source+Sans+Pro:600);
		@import 'https://fonts.googleapis.com/css?family=Cormorant';
		body{
			background-color: #9999ff;

		}
		.container{
			background-color: rgba(255,255,255,0.85);
			height: 500px;
			width: 60%;
			margin:0 auto;
			margin-top: 60px;
			-webkit-box-shadow:0 0 150px rgba(0,0,0,0.5);
			box-shadow: 0 0 150px rgba(0,0,0,0.5);	
			border-radius: 10px;	  	
		}
	 	.days{
	 		font-size: 25px;
			font-family: 'Cormorant', serif;
			color: #000;
			padding-left: 2vw;
	 	}
		.heading{
			font-size: 35px;
			text-align: center;
			color: #666;
			/*text-shadow: 0 0 4px rgb(0,0,0);*/
			font-family: 'Slabo ', serif;
			/*font-weight: bold;*/
			padding-top: 3vh;
		}
		.slots{
			padding-left: 4vw;
			color: #000;
			font-size: 20px;
		}
		.mdl-button{
			float: right;
			margin-right: 10px;
		}

	 </style>
</head>
<body>
	<div class="container">



		<h1 class="heading">Book your appointment</h1>
		<div class="form1">
			<form action="{% url 'portal:home' %}" method="POST">
			{% csrf_token %}
			<p>
				<div class="slots">

					{% if slots %}
						{% for x in slots %}
							{% if x.is_free %}	
					    		<p>
							      <input name="slot_time" value="{{x.display}}" type="radio" id="{{forloop.counter}}" >
							      <label for="{{forloop.counter}}"><b><font color="green">{{x.display}}</font></b></label>
							    </p>
							{% else %}
								<p>
							      <input type="radio" disabled="true" id="{{forloop.counter}}" >
							      <label for="{{forloop.counter}}"><b><font color="red">{{x.display}}</font></b></label>
							    </p>
							{% endif %}
						{% endfor %}
						<input type="submit" value="Submit" style="background-color:rgb(63,81,181); color: #fff; border-radius:5px; ">

				        <input type="hidden" value="{{admin.id}}" name="adminID">
			            <input type="hidden" value="{{client.id}}" name="clientID"> 
			            <input type="hidden" value="after_book" name="login_flag">
						
					{% else %}
						<p>No time slot</p>
			            <button onclick="goBack()">Back</button>

			      	{% endif %}
				
				</div>
			</p>
			</form>
        
		</div>
		<!-- <button  type="button" class="mdl-button">Confirm</button> -->
		<!-- <button class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--colored" id="show-dialog" type="button">
		  Confirm
		</button> -->
		<dialog class="mdl-dialog">
	    <h4 class="mdl-dialog__title">Confirm Appintment</h4>
	    <!-- <div class="mdl-dialog__content">
	      <p>
	        Confirm Appintment
	      </p>
	    </div> -->
	    <div class="mdl-dialog__actions">
	      <button type="button" id="show-dialog2" class="mdl-button mdl-js-button mdl-button--raised">ok</button>
	      <button type="button" class="mdl-button close mdl-js-button mdl-button--raised">Cancel</button>
	    </div>
	  </dialog>
	  <dialog class="mdl-dialog" id="dialog2">
	    <h3 class="mdl-dialog__title">Appointment Confirmed</h3>
	    <div class="mdl-dialog__content">
	      <p>
	        Your slot has been Booked. Be there!
	      </p>
	    </div>
	    <div class="mdl-dialog__actions">
	    	<button type="button" id="show-dialog3" class="mdl-button mdl-js-button mdl-button--raised ok">ok</button>
	    </div>
	   </dialog> 
	</div>
	<script>
	    var dialog = document.querySelector('dialog');
	    var showDialogButton = document.querySelector('#show-dialog');
	    if (! dialog.showModal) {
	      dialogPolyfill.registerDialog(dialog);
	    }
	    showDialogButton.addEventListener('click', function() {
	      dialog.showModal();
	    });
	    dialog.querySelector('.close').addEventListener('click', function() {
	      dialog.close();
	    });
	</script>

	<script>
		function goBack() {
		    window.history.back();
		}
	</script>


  </body>
</html>

portal/templates/base.html
<!DOCTYPE html>
<html>
	<head>
	    {% block title %}
	        <title>Psychology Portal IIITD</title>
	    {% endblock %}

	    {% block included_files %}
	    
	    {% endblock %}

	</head>

	<body>
		
		<div class="mdl-layout mdl-js-layout mdl-layout--fixed-header" style="margin-top:-15px;">
		    <header class="mdl-layout__header" style="background-color: rgba(255,255,255,0.05);">
		        <div class="mdl-layout__header-row"  style="background-color: rgba(255,255,255,0.05);">
		            <span class="mdl-layout-title">Psychology Portal IIITD</span>
		            <div class="mdl-layout-spacer"></div>
		            <nav class="mdl-navigation mdl-layout--large-screen-only">
		                <form id="form1" action="{% url 'portal:home' %}" method="post">
		                    {% csrf_token %}
		                    <a class="mdl-navigation__link" href="javascript:;" onclick="document.getElementById('form1').submit();">Home</a>
		                    <input type="hidden" name="login_flag" value="redirect" >
		                    <input type="hidden" name="userID" value="{{user.id}}">
		                
		                </form>

		                <form id="form2" action="{% url 'portal:about' user.id %}" method="post">
		                    {% csrf_token %}
		                    <a class="mdl-navigation__link" href="javascript:;" onclick="document.getElementById('form2').submit();">About</a>
		                
		                </form>
		                <!-- <a class="mdl-navigation__link" href="https://mail.google.com/mail/u/0/#inbox"><img src="gplus3.png" alt="login with google" style="width: 25px;"></img></a> -->
		            </nav>
		        </div>
		    </header>
		</div>
		
		{% block body %}

		{% endblock %}
	</body>

</html>



{% block script %}

{% endblock %}

portal/templates/layout.html
  {% extends 'base.html' %}
  {% block included_files %}
    <link rel="stylesheet" type="text/css" href="style.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://code.getmdl.io/1.1.3/material.indigo-pink.min.css">
    <script defer src="https://code.getmdl.io/1.1.3/material.min.js"></script>
    <style>
    @import url(https://fonts.googleapis.com/css?family=Source+Sans+Pro:600);
    @import 'https://fonts.googleapis.com/css?family=Cormorant';

  body{
    background-color: #9999ff;

  }
  .mdl-grid{
    background-color: #9999ff;
  }
      .demo-list {
        width: 650px;
      }
    
    .demo-card-wide.mdl-card {
      width: 750px;
      height: 480px;
      margin: 0 auto;
      margin-top: 30px;
    }
    .demo-card-wide > .mdl-card__title {
      color: #fff;
      height: 15px;
      margin-top: 0px;
/*    background: url('../assets/demos/welcome_card.jpg') center / cover;
*/  }
    .demo-card-wide > .mdl-card__menu {
      color: #fff;
    }
    .time{
        color: #c0c0c0;
        
    }
    .mdl-textfield {
        width: 600px;

    }
    .mdl-button {
        margin-bottom:0px;
        margin-right: 0px;
    }
    .card2{
        width: 750px;
        height: 80px;    /*100*/
        margin-bottom:0px;
        min-height: 50px;

    }
    #forms{
    margin-bottom: 0px;
    }
    .card3{
        margin:0 auto;
        margin-top: 30px;
        height: 480px;
        width: calc(20%);
        margin-right:calc(-10%);
        box-shadow: 0 0 100px rgba(0,0,0,0.6);
        float:left; margin-left:6vw;
        border-radius: 10px;
        background-color: rgba(255,255,255,0.95);

    }
    /*.mdl-card__title{
        height: calc(80% -5)
    }*/
    .buttons{
        margin: 0 auto;
        padding-top: 10px;
        width: 30px;

    }
    .mdl-grid{
        margin-top: 40px; /*CHange to increase*/
    }
    .card4{
      box-shadow: 0 0 100px rgba(0,0,0,0.6);
      float:right; margin-right:6vw;
      border-radius: 10px;
      background-color: rgba(255,255,255,0.95);
    }
    h6{
      color: #fff;
      font-size: 5px;
      padding-top: 7px;
    }
    li{
      list-style: none;
    }
    </style>
{% endblock %}

{% block body %}

  <button onclick="goBack()">Back</button>
    <div class="mdl-grid portfolio-max-width  mdl-cell mdl-cell--12-col mdl-cell--2-col-tablet mdl-card mdl-cell--15-col-desktop mdl-cell--7-col-phone">
    {% block grid %}    
        <!-- header -->
        <div class="mdl-grid mdl-cell mdl-cell--12-col mdl-cell--2-col-tablet mdl-card mdl-cell--15-col-desktop mdl-cell--7-col-phone"> 
        <div class="mdl-card mdl-shadow--6dp card3 mdl-cell--3-col-tablet mdl-cell--2-col-phone mdl-cell--3-col-desktop">
              {% block card_left %}
                  <div class="mdl-card__title">
                    <h2 class="mdl-card__title-text">
                      {% block card_left_title %}

                      {% endblock %}
                      </h2>

                  </div>
                  <div class="mdl-card__supporting-text" style="height:300px; overflow: scroll; overflow-x:hidden;">
                    {% block card_left_supporting_text %}
                    <ul class="demo-list-icon mdl-list">

                      {% block card_left_supporting_text_list %}

                      {% endblock %}
                    
                    </ul>
                    {% endblock %}
                  </div>
                  <div class="mdl-card__actions mdl-card--border">
                    
                  </div>
                  <!-- <div class="mdl-card__menu">
                    <button class="mdl-button mdl-button--icon mdl-js-button mdl-js-ripple-effect">
                      <i class="material-icons">share</i>
                    </button>
                  </div> -->
                    <div style="size:5px;">
                    {% block card_left_buttons %}

                      {% endblock %}
                    </div>    
                {% endblock %}
            </div>

            <div class="demo-card-wide mdl-card mdl-shadow--6dp mdl-cell mdl-cell--7-col-tablet mdl-cell--4-col-phone mdl-cell--10-col-desktop card4"> 
             {% block card_right %}

                    <div class="mdl-card__title" style="margin-top:2.5%;">
                        <h2 class="mdl-card__title-text " style="color:black; ">
                          {% block card_right_title %}

                          {% endblock %}
                          </h2>

                  </div>

                    <div id="scroll_bottom" class="mdl-card__supporting-text" style="height:300px; overflow: scroll; overflow-x:hidden;">
                          
                      {% block card_right_supporting_text %}    

       
                      {% endblock %}    
                    </div>

               

                <div class="mdl-card__menu">
                    <button class="mdl-button mdl-button--icon mdl-js-button mdl-js-ripple-effect">
                    <i class="material-icons">share</i>
                    </button>
                </div>
                <div class="mdl-card card2">
                    {% block card_right_bottom %}    
                    
                    {% endblock %}    
                </div>  
            
             {% endblock %}
            </div>
            
    </div>
    {% endblock %}
</div>
 
    
  {% endblock %}

portal/templates/navbar.html
<link rel="stylesheet" href="https://code.getmdl.io/1.1.3/material.indigo-pink.min.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<script defer src="https://code.getmdl.io/1.1.3/material.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"></script>
<style type="text/css">
  @import url(https://fonts.googleapis.com/css?family=Source+Sans+Pro:600);
  @import 'https://fonts.googleapis.com/css?family=Cormorant';
    body{
      background-color: #9999ff;
      font-family: 'Source Sans Pro', sans-serif;
    }
    #login_text{
        font-size: 30px;
        font-family: 'Source Sans Pro', sans-serif;
        margin-left: 2vw;
        font-weight: bold;
        margin-top: 60px;
    }
    #logout_link{
        text-decoration: none;
        color: #000;
    }
    a{
        text-decoration: none;
        font-size: 20px;
        color: #000;
    }
    li{
        text-decoration: none;
        list-style: none;
        display: block;
    }
    #usernames{
        font-size: 30px;
        margin-left: 2vw;
        margin-top: 60px;
    }
    h6{
        color: #fff;
        font-size: 6px;
        padding-top: 7px;
    }
    .mdl-js-button{
        box-shadow: 0 0 10px rgba(0,0,0,0.3);
    }
    #main_div{
        box-shadow: 0 0 50px rgba(0,0,0,0.5);
        height: 120px;
        width:400px;
        border-radius: 10px;
        padding:5px;
    }
</style>
<div class="mdl-layout mdl-js-layout mdl-layout--fixed-header" style="margin-top:-15px;">
    <header class="mdl-layout__header" style="background-color: rgba(255,255,255,0.05);">
        <div class="mdl-layout__header-row"  style="background-color: rgba(255,255,255,0.05);">
            <span class="mdl-layout-title">Psychology Portal IIITD</span>
            <div class="mdl-layout-spacer"></div>
            <nav class="mdl-navigation mdl-layout--large-screen-only">
                <form id="form1" action="{% url 'portal:home' %}" method="post">
                    {% csrf_token %}
                    <a class="mdl-navigation__link" href="javascript:;" onclick="document.getElementById('form1').submit();">Home</a>
                    <input type="hidden" name="login_flag" value="redirect" >
                    <input type="hidden" name="userID" value="{{user.id}}">
                
                </form>

                <form id="form2" action="{% url 'portal:about' user.id %}" method="post">
                    {% csrf_token %}
                    <a class="mdl-navigation__link" href="javascript:;" onclick="document.getElementById('form2').submit();">About</a>
                
                </form>
                <!-- <a class="mdl-navigation__link" href="https://mail.google.com/mail/u/0/#inbox"><img src="gplus3.png" alt="login with google" style="width: 25px;"></img></a> -->
            </nav>
        </div>
    </header>
</div>

<br>
<br>
<br>
<br>

portal/templates/p_chat_userchat.html
<li class="mdl-list__item mdl-list__item--three-line">
	<span class="mdl-list__item-primary-content">
	  <i class="material-icons mdl-list__item-avatar">person</i>
	  {% if x.by_admin %}
	  		<span>{{x.admin}}(Admin) <span class="time">{{x.pub_date}}</span></span>
	  {% else %}
	        <span>{{x.client}} <span class="time">{{x.pub_date}}</span></span>
	  {% endif %}
	  <span class="mdl-list__item-text-body">
	     {{ x.text }}
	  </span>
	</span>
	<span class="mdl-list__item-secondary-content">
	  <a class="mdl-list__item-secondary-action" href="#" style="color:#8533ff;"><i class="material-icons">more_vert</i></a>
	</span>
</li>